server:
  port: 20000

############################ HTTP START ############################################
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lee9213/micro-services.git
          skipSslValidation: true
      name: git
  application:
    name: spring-cloud-config-git-service
############################ HTTP END ############################################