server:
  port: 20000

############################ HTTP START ############################################
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lee9213/spring-cloud-config-files.git
          skipSslValidation: true
  application:
    name: spring-cloud-config-git-service
############################ HTTP END ############################################