server:
  port: 20000
spring:
  application:
    name: spring-cloud-config-git-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lee9213/spring-cloud-config-files.git