server:
  port: 42000
spring:
  application:
    name: spring-cloud-gateway-service
  cloud:
    zookeeper:
      discovery:
        metadata:
          management:
            port: 43000
    # 路由配置
    gateway:
      routes:
        - id: gmall-sso
          uri: lb://gmall-sso
          predicates:
            - Path=/login/**
# 健康检查端口配置
management:
  server:
    port: 43000
  # 显示健康具体信息
  endpoint:
    health:
      show-details: always
  # 开放所有页面端点
  endpoints:
    web:
      exposure:
        include: "*"

# Eureka 配置
#eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 10
#    health-check-url-path: /actuator/health
#  client:
#    registry-fetch-interval-seconds: 5
#    service-url:
#      defaultZone: http://www:lee9213:com:20000/eureka/
